### ISSUE TITLE
[BUG] ImportError: cannot import name 'save_checkpoint' from 'utils' pix2pix\custom\utils.py

### ISSUE THREAD

**Issue by firmium** [eduardpauliuc/fedpix#1]
**Describe the bug**
ImportError: cannot import name 'save_checkpoint' from 'utils' (D:\dev\ai\fedpix\pix2pix\custom\utils.py)

**Comment by eduardpauliuc** [comment]
Fixed in a09c574d3c099cdae76989aedf87fbd85b240408
